### ISSUE TITLE
Questions on config for this keycloak jasper util in CE version

### ISSUE THREAD

**Issue by heregear** [nico-arianto/jasperserver-war-keycloak#1]
Hi Nico,

At this point I've built your custom war, then deployed it w/buildomatic (CE version).  In JrsExternalKeycloakAuthenticationSuccessHandler, in afterPropertiesSet() method, I'm getting an exception thrown for Assert.notNull(this.externalDataSynchronizer, "externalDataSynchronizer cannot be null");

Any ideas?  This sounds like some type of config issue - probably something I'm not familiar with on the jasper side...

My environment: Windows 7, Tomcat 8, Keycloak 1.9.1, build is working fine

What I've done:
-added some debug logging
-successfully built the war
-deployed files applicationContext-externalAuth-Keycloak.xml,  master.json, slave.json to the root of WEB-INF
-build the jar, then deployed with js-ant deploy-webapp-ce
-run up tomcat, that's when I start seeing my debug msgs whereby it's complaining about a null externalDataSynchronizer
-try to login to jasper, then I get a j_spring_security_check exception

Is there some config file missing here?  I'm referencing this cookbook:  http://community.jaspersoft.com/documentation/jasperreports-server-authentication-cookbook/beans.

**Is there something I need to do with some other jasper spring bean config file, like  	proxyAuthenticationProcessingFilter?

One last question:  have you successfully used this in CE and PRO versions of jasper server?
Also - have you updated this for future versions of keycloak?  We're on 2.4.0.Final...

Thanks

**Comment by nico-arianto** [comment]
You will not find any info about this error in jasper report cookbook, because this is the custom classes that we're going to included in the custom WAR.

Looks into [applicationContext-externalAuth-Keycloak.xml](https://github.com/nico-arianto/jasperserver-war-keycloak/blob/master/src/main/webapp/WEB-INF/applicationContext-externalAuth-Keycloak.xml) file.

We have successfully integrated with CE and PRO for the Jasper 6.2.0 Final.

I never tested for Keycloak 2.4.0.Final.

**Comment by nico-arianto** [comment]
I closed issue.
